"""update_kvm_hosts_schema

Revision ID: 727bcfa25c1f
Revises: 001_initial
Create Date: 2025-11-12 21:32:59.291314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '727bcfa25c1f'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.drop_constraint('api_tokens_user_id_fkey', 'api_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'api_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_tokens', 'updated_at')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_column('audit_logs', 'updated_at')
    op.create_index(op.f('ix_backup_schedules_id'), 'backup_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_backup_schedules_storage_backend_id'), 'backup_schedules', ['storage_backend_id'], unique=False)
    op.drop_column('backup_schedules', 'updated_at')
    op.add_column('backups', sa.Column('backup_type', sa.Enum('daily', 'weekly', 'monthly', 'yearly', 'archival', 'custom', name='scheduletype'), nullable=False))
    op.add_column('backups', sa.Column('tags', sa.JSON(), nullable=True))
    op.alter_column('backups', 'size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('backups', 'compressed_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_backups_name', table_name='backups')
    op.create_index(op.f('ix_backups_backup_type'), 'backups', ['backup_type'], unique=False)
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_index(op.f('ix_backups_source_type'), 'backups', ['source_type'], unique=False)
    op.create_index(op.f('ix_backups_storage_backend_id'), 'backups', ['storage_backend_id'], unique=False)
    op.drop_column('backups', 'name')
    op.drop_column('backups', 'updated_at')
    op.drop_column('backups', 'schedule_type')
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.drop_column('containers', 'updated_at')
    op.add_column('job_logs', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_job_logs_id'), 'job_logs', ['id'], unique=False)
    op.drop_column('job_logs', 'metadata')
    op.drop_column('job_logs', 'updated_at')
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_column('jobs', 'progress')
    op.drop_column('jobs', 'updated_at')
    op.add_column('kvm_hosts', sa.Column('uri', sa.String(length=255), nullable=False))
    op.add_column('kvm_hosts', sa.Column('auth_type', sa.String(length=50), nullable=False))
    op.add_column('kvm_hosts', sa.Column('last_sync', sa.String(length=50), nullable=True))
    op.alter_column('kvm_hosts', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('kvm_hosts', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_kvm_hosts_hostname', table_name='kvm_hosts')
    op.create_index(op.f('ix_kvm_hosts_id'), 'kvm_hosts', ['id'], unique=False)
    op.drop_column('kvm_hosts', 'port')
    op.drop_column('kvm_hosts', 'hostname')
    op.drop_column('kvm_hosts', 'updated_at')
    op.drop_column('kvm_hosts', 'ssh_key')
    op.create_index(op.f('ix_notification_configs_id'), 'notification_configs', ['id'], unique=False)
    op.drop_column('notification_configs', 'updated_at')
    op.add_column('notifications', sa.Column('type', sa.Enum('email', 'webhook', name='notificationtype'), nullable=False))
    op.add_column('notifications', sa.Column('subject', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'updated_at')
    op.add_column('podman_hosts', sa.Column('uri', sa.String(length=255), nullable=False))
    op.add_column('podman_hosts', sa.Column('last_sync', sa.String(length=50), nullable=True))
    op.alter_column('podman_hosts', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index('ix_podman_hosts_hostname', table_name='podman_hosts')
    op.create_index(op.f('ix_podman_hosts_id'), 'podman_hosts', ['id'], unique=False)
    op.drop_column('podman_hosts', 'socket_path')
    op.drop_column('podman_hosts', 'updated_at')
    op.drop_column('podman_hosts', 'port')
    op.drop_column('podman_hosts', 'username')
    op.drop_column('podman_hosts', 'hostname')
    op.drop_column('podman_hosts', 'ssh_key')
    op.alter_column('storage_backends', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_storage_backends_id'), 'storage_backends', ['id'], unique=False)
    op.drop_column('storage_backends', 'updated_at')
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.drop_column('system_settings', 'updated_at')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'updated_at')
    op.create_index(op.f('ix_vms_id'), 'vms', ['id'], unique=False)
    op.drop_column('vms', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_vms_id'), table_name='vms')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('system_settings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.add_column('storage_backends', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_storage_backends_id'), table_name='storage_backends')
    op.alter_column('storage_backends', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('podman_hosts', sa.Column('ssh_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('podman_hosts', sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('podman_hosts', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('podman_hosts', sa.Column('port', sa.INTEGER(), server_default=sa.text('22'), autoincrement=False, nullable=False))
    op.add_column('podman_hosts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('podman_hosts', sa.Column('socket_path', sa.VARCHAR(length=500), server_default=sa.text("'/run/podman/podman.sock'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_podman_hosts_id'), table_name='podman_hosts')
    op.create_index('ix_podman_hosts_hostname', 'podman_hosts', ['hostname'], unique=False)
    op.alter_column('podman_hosts', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('podman_hosts', 'last_sync')
    op.drop_column('podman_hosts', 'uri')
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'subject')
    op.drop_column('notifications', 'type')
    op.add_column('notification_configs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notification_configs_id'), table_name='notification_configs')
    op.add_column('kvm_hosts', sa.Column('ssh_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('kvm_hosts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('kvm_hosts', sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('kvm_hosts', sa.Column('port', sa.INTEGER(), server_default=sa.text('22'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_kvm_hosts_id'), table_name='kvm_hosts')
    op.create_index('ix_kvm_hosts_hostname', 'kvm_hosts', ['hostname'], unique=False)
    op.alter_column('kvm_hosts', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('kvm_hosts', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('kvm_hosts', 'last_sync')
    op.drop_column('kvm_hosts', 'auth_type')
    op.drop_column('kvm_hosts', 'uri')
    op.add_column('jobs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.add_column('job_logs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('job_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_job_logs_id'), table_name='job_logs')
    op.drop_column('job_logs', 'timestamp')
    op.add_column('containers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.add_column('backups', sa.Column('schedule_type', postgresql.ENUM('daily', 'weekly', 'monthly', 'yearly', 'archive', name='scheduletype'), autoincrement=False, nullable=False))
    op.add_column('backups', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('backups', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_backups_storage_backend_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_source_type'), table_name='backups')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_backup_type'), table_name='backups')
    op.create_index('ix_backups_name', 'backups', ['name'], unique=False)
    op.alter_column('backups', 'compressed_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('backups', 'size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('backups', 'tags')
    op.drop_column('backups', 'backup_type')
    op.add_column('backup_schedules', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_backup_schedules_storage_backend_id'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_id'), table_name='backup_schedules')
    op.add_column('audit_logs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.add_column('api_tokens', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_tokens', type_='foreignkey')
    op.create_foreign_key('api_tokens_user_id_fkey', 'api_tokens', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    # ### end Alembic commands ###
