"""change_backup_size_columns_to_bigint

Revision ID: 85559dbd3945
Revises: 12b961585c61
Create Date: 2025-11-13 17:00:45.453220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85559dbd3945'
down_revision = '12b961585c61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backups', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('backups', 'compressed_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_index(op.f('ix_backups_backup_mode'), 'backups', ['backup_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backups_backup_mode'), table_name='backups')
    op.alter_column('backups', 'compressed_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('backups', 'size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
